blank_issues_enabled: true

contact_links:
  - name: 'Share feedback as an Learn-OCaml teacher or learner'
    url: https://github.com/learn-ocaml-community/teaching-feedback/issues/new/choose
    about: >-
      This is a new place to share feedback within the learn-ocaml-community organization.
