#!/bin/bash
# href: https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing
# href: https://microbadger.com/labels

echo "### Building with custom build arguments"

die() {
    echo >&2 "### ERROR: $*"
    exit 1
}

echo "DOCKERFILE_PATH: ${DOCKERFILE_PATH}"
echo "DOCKER_TAG: ${DOCKER_TAG}"
echo "IMAGE_NAME: ${IMAGE_NAME}"
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"

# SOURCE_COMMIT is already provided:
# No need for VCS_REF=$(git rev-parse --short HEAD)

VCS_REF="${SOURCE_COMMIT:0:7}"
[ $? -eq 0 ] || die "The substitution failed."
echo "VCS_REF: ${VCS_REF}"


BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") || die "The date command failed."
echo "BUILD_DATE: ${BUILD_DATE}"

exec docker build --rm --force-rm \
  --build-arg=BUILD_DATE="${BUILD_DATE}" \
  --build-arg=VCS_BRANCH="${SOURCE_BRANCH}" \
  --build-arg=VCS_REF="${VCS_REF}" \
  -f "${DOCKERFILE_PATH}" -t "${IMAGE_NAME}" .
