(-noautolink
 -cclib -Wl,-Bstatic
 -cclib -lcamlstr
 -cclib -llaolao_stubs
 -cclib -lbase_stubs
 -cclib -lssl_threads_stubs
 -cclib -lssl
 -cclib -llwt_unix_stubs
 -cclib -lcrypto
 -cclib -lthreadsnat
 -cclib -lcstruct_stubs
 -cclib -lbigarray
 -cclib -lunix
 -cclib -Wl,-Bdynamic
 -cclib -static-libgcc
 -cclib -lpthread)
